apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: mattermost-minio-host-path-exception
  namespace: mattermost-minio
spec:
  exceptions:
  - policyName: restrict-host-path-write
    ruleNames:
    - require-readonly-hostpath
  match:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - mattermost-minio
        names:
        - minio-post-job-*
