name: lula-lint

permissions:
  contents: read

defaults:
  run:
    # We need -e -o pipefail for consistency with GitHub Actions' default behavior
    shell: bash -e -o pipefail {0}

on:
  pull_request:
    branches:
      - main
    paths:
      - "oscal-component.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo and setup the tooling for this job
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          ref: ${{ github.head_ref }}

      - name: Lula Setup
        uses: defenseunicorns/lula-action/setup@9cf0c7fa5cdd40b55ccab87fe389bb631f32f03b

      - name: Lula Lint
        uses: defenseunicorns/lula-action/lint@9cf0c7fa5cdd40b55ccab87fe389bb631f32f03b
        with:
          oscal-target: "oscal-component.yaml"
